// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_Tg-9xocvyB09LZpWswtBUEtMF_mIXbE',
    appId: '1:140598841934:web:1490187634554f9ee6291f',
    messagingSenderId: '140598841934',
    projectId: 'my-notes-flutter-kwaku',
    authDomain: 'my-notes-flutter-kwaku.firebaseapp.com',
    storageBucket: 'my-notes-flutter-kwaku.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD455_tmtiokwpuxI3lBMgqwQ8WeCD7mHI',
    appId: '1:140598841934:android:ac391fcde9744da2e6291f',
    messagingSenderId: '140598841934',
    projectId: 'my-notes-flutter-kwaku',
    storageBucket: 'my-notes-flutter-kwaku.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByrZznAFImNZHRHWcN4ACfs85ReVO2ULg',
    appId: '1:140598841934:ios:6b7143f2092e744ae6291f',
    messagingSenderId: '140598841934',
    projectId: 'my-notes-flutter-kwaku',
    storageBucket: 'my-notes-flutter-kwaku.appspot.com',
    iosBundleId: 'com.kwakudapaah.mynotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyByrZznAFImNZHRHWcN4ACfs85ReVO2ULg',
    appId: '1:140598841934:ios:db3482401ce775d1e6291f',
    messagingSenderId: '140598841934',
    projectId: 'my-notes-flutter-kwaku',
    storageBucket: 'my-notes-flutter-kwaku.appspot.com',
    iosBundleId: 'com.kwakudapaah.mynotes.RunnerTests',
  );
}
